version: '3'
services:
  web:
    image: golang
    working_dir: /go/src
    stdin_open: true
    command: go run main.go
    environment:
      - SERVICE_URL=https://qc05n0gp78.execute-api.eu-central-1.amazonaws.com/prod/BackendGoChallenge?id=
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src
